version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2.31
    container_name: ripley_clickhouse
    network_mode: host
    logging:
      driver: none
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16

  s3:
    image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
    network_mode: host
    logging:
      driver: none
    command:
      - server
      - --address=localhost:9001
      - /data
    environment:
      - MINIO_ROOT_USER=ripley_key
      - MINIO_ROOT_PASSWORD=ripley_secret
